title: Reni Susanti
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://renisusanti.my.id
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github:
   twitter:
   facebook: cleo.reni
   email: reni4susanti@gmail.com

google_analytics: UA-67920972-2
